services:
  - type: web
    name: ai-task-api
    env: python
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir --prefer-binary
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1